title: Reference
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dorsetgeology.github.io/reference

aux_links:
  Template Repository: https://github.com/dorsetgeology/referenc

plugins: 
jekyll-scholar
